### ISSUE TITLE
genetic algorithm without mating?

### ISSUE THREAD

**Issue by droundy** [joeylmaalouf/genetic-algorithm-package#1]
When I examine the code, it looks like the top individuals do not contribute to the creation of new individuals.  Thus it seems like this package is missing a key element of what makes genetic algorithms evolve.  Am I wrong?

Would a pull request implementing mating be accepted?

I like the API of genalg, but am getting rather disappointing results out of it in terms of actual optimization.

**Comment by joeylmaalouf** [comment]
Oh, absolutely! It's been a while since I've worked on this, but I'm definitely willing to look at any pull requests submitted. Thanks for getting involved!

**Comment by joeylmaalouf** [comment]
Finally got around to updating the pip package with the PR mentioned above.
